package com.bluedragonss.boysss;

/* This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int icon = 2130771968;
    }

    public static final class id {
        public static final int menu_settings = 2130837504;
    }

    public static final class layout {
        public static final int activity_main = 2130903040;
    }

    public static final class menu {
        public static final int activity_main = 2130968576;
    }

    public static final class string {
        public static final int app_name = 2131034112;
        public static final int banner_ad_unit_id = 2131034113;
        public static final int hello_world = 2131034114;
        public static final int menu_settings = 2131034115;
    }

    public static final class style {
        public static final int AppBaseTheme = 2131099648;
        public static final int AppTheme = 2131099649;
    }
}
